_wandb:
    value:
        cli_version: 0.25.0
        e:
            qkg5hsfjg05pv9qeypcodkkc6920q4lo:
                codePath: c:\Users\lucas\Documents\MSE\4_Semester\deep-learning-mpw\01_MPW-CNN\notebooks\CNN-optimizers.ipynb
                codePathLocal: CNN-optimizers.ipynb
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "1999348166656"
                        used: "393766105088"
                email: lucas.j.keller98@gmail.com
                executable: c:\Users\lucas\Documents\MSE\4_Semester\FTP_DeLearn\venv_DeLearn\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 8960
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-8ed3d629-4b03-2564-daf8-63b7610dc8e2
                host: Lucas-PC
                memory:
                    total: "33407385600"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\lucas\Documents\MSE\4_Semester\deep-learning-mpw\01_MPW-CNN\notebooks\CNN-optimizers.ipynb
                python: CPython 3.11.9
                root: c:\Users\lucas\Documents\MSE\4_Semester\deep-learning-mpw\01_MPW-CNN\notebooks
                startedAt: "2026-04-04T19:01:55.575207Z"
                writerId: qkg5hsfjg05pv9qeypcodkkc6920q4lo
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 13
                - 16
                - 62
            "4": 3.11.9
            "5": 0.25.0
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.25.0
            "13": windows-amd64
base_channels:
    value: 32
batch_size:
    value: 64
depth:
    value: 14
device:
    value: cuda
do:
    value: 0.5
dropout:
    value: 0
epochs:
    value: 20
in_channels:
    value: 3
inputsize:
    value: 224
loss:
    value: CrossEntropyLoss
lr:
    value: 0.001
max_channels:
    value: 256
num_classes:
    value: 10
num_parameters:
    value: 4717802
num_workers:
    value: 0
optimizer_name:
    value: RMSprop
optimizers:
    value:
        - SGD
        - MomentumNesterov
        - RMSprop
        - Adam
pin_memory:
    value: true
use_wandb:
    value: true
wandb_entity:
    value: MSE_DeLearn_SPR26
wandb_log_freq:
    value: 100
wandb_mode:
    value: online
wandb_project:
    value: MPW-CNN
wandb_watch:
    value: false
